signals:
  - momentum
  - reversal
  - beta
ic: .05
signal-combinator: mean
constraints:
  - full-investment
  - long-only
  - no-buying-on-margin
  - unit-beta
gamma: 300
decimal-places: 4
data-date: 2025-12-30
earliest-backtest-date: 1995-07-31
ignore-tickers:
  - MONDQ
  - VELO
  - BGXXQ
  - PSTX.CVR
broker: ibkr